name: .NET-CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - os: windows-latest
            rid: win-x64
            buildName: Windows
          - os: macos-latest
            rid: osx-x64
            buildName: Mac-OS
          - os: ubuntu-latest
            rid: linux-x64
            buildName: Linux

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Publish
      run: dotnet publish src -c Release -o publish -r ${{ matrix.rid }} --no-self-contained --verbosity normal
    - name: Prepare Publish Directory
      run: |
        cp LICENSE publish
        cp README.md publish
    - name: Upload Artifact
      uses: actions/upload-artifact@v3.1.0  
      with:
        name: ${{ github.event.repository.name }}-${{ matrix.buildName }}
        path: |
          publish
          !publish/*.pdb
